---
name: Kevin Howell
markdown: redcarpet
highlighter: rouge
nav_pages:
  home: "/"
  bio: "/bio"
  projects: "/projects"
  presentations: "/presentations"
  links: "/links"
tags_to_show:
- angularjs
- c
- c++
- cordova
- eclipse
- fedora
- fuzzer
- gles
- guice
- java
- maven
- mobile
- opengl
- physicsfs
- pouchdb
- project
- python
- python 3
- recipe
- refactoring
- rpm
- thunderbird
- tips
- xml
- xpcom
- xsd
